version: "3.8"
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro # third party image, please keep notice what you are doing
    restart: unless-stopped
    environment:
      - RPC_SECRET=your_aria_rpc_token # aria rpc token, customize your own
      - RPC_PORT=6800

  vfoy:
    container_name: vfoy
    image: jaylenwa/vfoy:1.0.0
    restart: unless-stopped
    volumes:
      - ./vfoy/data:/data
      - ./vfoy/uploads:/vfoy/uploads
      - ./vfoy/avatar:/vfoy/avatar
    depends_on:
      - aria2
      - redis
    ports:
      - 80:1214
